FROM nginx:1.23

RUN apt-get update && apt-get install -y openssl libssl-dev curl git

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    export PATH="$HOME/.cargo/bin:$PATH" && \
    cd /tmp \
    && git clone https://github.com/cloudflare/quiche.git \
    && cd quiche \
    && QUICHE_BSSL_PATH=`pwd`/../boringssl \
    && LD_LIBRARY_PATH=$QUICHE_BSSL_PATH/target/debug:$LD_LIBRARY_PATH \
    && cargo build --manifest-path ./http3/Cargo.toml --features ffi \
    && cp ./target/debug/libquiche.so /usr/lib/ \
    && cp ./target/debug/libquiche.a /usr/lib/ \
    && cp -R ./include/* /usr/include/

COPY ./ /etc/nginx/

EXPOSE 80
EXPOSE 443