FROM node:18-alpine

WORKDIR /app

COPY ./package.json .

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --shamefully-hoist

COPY . .

ENV PATH ./node_modules/.bin/:$PATH
ENV NODE_ENV=development

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000
EXPOSE 24678