FROM node:18 AS builder

WORKDIR /app/

COPY ./package.json .

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --shamefully-hoist

COPY . .

RUN pnpm run build


FROM node:18-alpine AS production

WORKDIR /app/

ENV NODE_ENV=production

COPY --from=builder /app/.output /app/.output