name: Release
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
  workflow_dispatch:
jobs:
  # build:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout the repo
  #       uses: actions/checkout@v3
  #     - name: Build Images
  #       run: docker-compose -f docker-compose.build.yml build
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #     - name: Push image to Docker Hub
  #       run: docker-compose -f docker-compose.build.yml push
  deploy:
    # needs: build
    runs-on: ubuntu-22.04
    # if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Copy docker-compose file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          source: "docker-compose.deploy.yml"
          rm: true
          target: "/opt/dcup"
      - name: Pull and run images
        uses: appleboy/ssh-action@v0.1.5
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          port: 22
          envs: username, password
          script: |
            echo $passowrd | docker login -u $username --password-stdin
            docker stop -t 5 $(docker ps -q)
            docker system prune -a
            docker-compose -f /opt/dcup/docker-compose.deploy.yml pull
            docker-compose -f /opt/dcup/docker-compose.deploy.yml up nuxt nginx

