name: Release
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Build Images
        run: docker-compose -f docker-compose.build.yml build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to Docker Hub
        run: docker-compose -f docker-compose.prod.yml push
