FROM python:3.9-slim

WORKDIR /code/

RUN pip install torch==1.13.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 9988